# dvc.yaml
stages:
  get_data:
    cmd: python scripts/data.py
    deps:
      - scripts/data.py
    params:
      - index_col
    outs:
      - data/initial_data.csv
  fit_model:
    cmd: python scripts/fit.py
    deps:
      - data/initial_data.csv
      - scripts/fit.py
    params:
      - target_col
      - one_hot_drop
      - iterations
      - depth
      - loss_function
    outs:
      - models/fitted_model.pkl
      - data/prepared_data.csv
  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
      - models/fitted_model.pkl
      - data/prepared_data.csv
      - scripts/evaluate.py
    params:
      - target_col
      - n_splits
      - n_jobs
      - metrics
    outs:
      - cv_results/cv_res.json